name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics 1
        uses: lowlighter/metrics@latest
        with:
          # Your Github token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: metrics1.svg
          user: pratamatama
          base: header, activity, repositories, metadata
          config_timezone: Asia/Jakarta
          config_twemoji: yes
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 2%
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit, pull_request, issue
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, editor-graphs, os, os-graphs
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: pratamatama
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_activity: yes
          plugin_activity_limit: 3
      
      
      - name: Metrics 2
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: metrics2.svg
          user: pratamatama
          base: ""
          config_timezone: Asia/Jakarta
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          use_prebuilt_image: yes
